steps:
# Pull the previous image to --cache-from
- id: 'pull previous image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'] # _IMAGE_NAME is a custom substitution

# Build the new image 
- id: 'build image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '--cache-from', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest', 
    '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest',
    '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID', 
    '.' 
  ]

# Push updated image
- id: 'push image'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID"]

# Replace the image tag in the k8s Deployment
- id: 'update manifest file'
  name: 'ubuntu'
  args: [ 
    'sed', '-i',
    's|gcr.io/$PROJECT_ID/$_IMAGE_NAME:.*|gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID|g', 
    'k8s.yml'
  ]

# Commit k8s.yml change to the repo
- id: 'commit update manifest to repo'
  name: 'gcr.io/cloud-builders/git'
  args: [
    '-c', 'user.email=""',
    '-c', 'user.name="GCB Worker"',
    'commit', '-a', '-m',
    'Update k8s Deployment image to tag $BUILD_ID [ci skip]',
    '-v'
  ]

# Push change to GitHub repo using encrypted secret
- id: 'git push change' 
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: [
    '-c',
    'git push https://$$GITHUB_TOKEN@github.com/christophersanson/js-demo-be.git master -v'
  ]
  secretEnv: ['GITHUB_TOKEN']

# Apply change
- id: 'kubectl apply updated manifest'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gcb-demo'

# Check rollout status
- id: 'check rollout status'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['rollout', 'status', 'deployment/js-demo-be']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gcb-demo'

# Associate image that was pushed to GCR with the build history UI
images:
- 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID'

# Encrypt Github token for push changes
secrets:
- kmsKeyName: projects/csanson-test/locations/global/keyRings/js-demo-be/cryptoKeys/github-token
  secretEnv:
    GITHUB_TOKEN: CiQAbhNgM1F4lsL8uNZHUbtwGVmGGXgv+VVxCn03Oa28xs5ccRwSUADhjamOVE7JpLxxbws/TxqECnR5BawRxUNzHNB5GCmCzP9nxA1s+1wneXmN+Z463yWoqFPpJ+ekYN0M1BZ9+QxauwTqNuSJ5G3kJJ4yy2Hl
