steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/js-demo-be-test', '-f', 'Dockerfile.test', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '-i', 'gcr.io/$PROJECT_ID/js-demo-be-test']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/js-demo-be:$BRANCH_NAME', '.' ]
images:
- 'gcr.io/$PROJECT_ID/js-demo-be:$BRANCH_NAME'